routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('config:clear');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('view:cache');
    return 'DONE'; //Return anything
});
Route::get('localization/{locale}','LocalizationController@lang');

Route::get('/', 'WelcomeController@index')->name('welcome.page');
// Route::post('/price/filter','WelcomeController@filterprice')->name('price.filter');

// Route::get('/layouts3', 'WelcomeController@layout')->name('layouts.new');
// show View all , Special , New , Popular , Top Selling Prodcts


Route::get('/new/arrival','WelcomeController@newarrival')->name('new.arrival');
Route::get('/hot/product','WelcomeController@hotproduct')->name('hot.product');
Route::get('/feature/product','WelcomeController@featureproduct')->name('feature.product');
Route::get('/category/list/{id}','WelcomeController@Categorylist')->name('category.list');
Route::get('/Subcategory/list/{id}','WelcomeController@SubCategorylist')->name('subcategory.list');
Route::get('/deals','WelcomeController@deals');


Route::get('/products/list/{id}','WelcomeController@productslist')->name('products.list');

Route::get('setpassword/{token}','EmailController@setpassword');

Route::get('sendemail','EmailController@sendemail');

Route::get('/careers','WelcomeController@careers');
Route::post('/careers','WelcomeController@careersPost');

Route::get('/faq','WelcomeController@faq');
Route::POST('/faq','WelcomeController@faqPost');

Route::get('/contact','WelcomeController@contact');

Route::get('/termsandconditions','WelcomeController@termsandconditions');

Route::get('/privacyandpolicy','WelcomeController@privacyandpolicy');

Route::get('/about','WelcomeController@about');

Route::get('/help','WelcomeController@help');

Route::post('sendproductemail','WelcomeController@sendproductemail');

Route::post('subscribe','WelcomeController@subscribe');

// cart added
Route::post('/cart/add/{id}','WelcomeController@cartadd')->name('cart.added');
Route::get('/checkout/cart','WelcomeController@checkoutcart')->name('checkout.cart');
Route::get('remove/cart/{rowId}','WelcomeController@removeCart')->name('remove.cart');

Route::get('/api-test' ,'WelcomeController@paymenttest');



Auth::routes();



Route::get('/c/setpassword/{passwordtoken}', 'Auth\AdminLoginController@setpassword');
Route::post('/c/setpassword', 'Auth\AdminLoginController@setpasswordPost');
Route::get('/c/login', 'Auth\AdminLoginController@showCompanyLoginForm');
Route::post('/c/login', 'Auth\AdminLoginController@companyloginpost')->name('company.login.submit');


Route::prefix('c')->middleware('checkcompany')->group(function() {
    Route::get('/', 'CompaniesAdminController@index');
    Route::get('/categories','c\CategoriesController@index');
    Route::get('/categories/form','c\CategoriesController@create');
    Route::post('/categories/form','c\CategoriesController@store')->name('add.company.categories');
    Route::get('/categories/form/{id}','c\CategoriesController@edit')->name('edit.company.categories');
    Route::post('/categories/form/{id}','c\CategoriesController@update')->name('update.company.categories');
    Route::get('/categories/delete{id}','c\CategoriesController@delete')->name('delete.company.categories');
    Route::get('/categories/trash','c\CategoriesController@categoriesTrash')->name('trash.company.categories');

    Route::get('/subcategories','c\CategoriesController@subcategories');
    Route::get('/subcategories/form','c\CategoriesController@subcategoriesform');
    Route::post('/subcategories/form','c\CategoriesController@subcategoriesformpost');
    Route::get('/subcategories/edit/{id}','c\CategoriesController@subcategoriesformedit');
    Route::post('/subcategories/formeditpost','c\CategoriesController@subcategoriesformeditpost');
    Route::get('/subcategories/trash','c\CategoriesController@trashsubcategories')->name('trash.company.subcategories');
    Route::get('/subcategories/delete/{id}','c\CategoriesController@subcategories_delet')->name('subcategories.company.delete');


    Route::get('/brands','c\CategoriesController@brands');

    Route::get('/barnds/add','c\CategoriesController@addbrands')->name('add.company.brands');
    Route::post('/barnds/store','c\CategoriesController@storebrands')->name('brands.company.create');
    Route::get('/brands/edit/{id}','c\CategoriesController@editbrand')->name('brands.company.edit');
    Route::post('/brands/update/{id}','c\CategoriesController@updatebrand')->name('brnads.company.update');
    Route::get('/brands/delete/{id}','c\CategoriesController@deletebrand')->name('brnads.company.delete');
    Route::get('/brands/delete/{id}','c\CategoriesController@deletebrand')->name('brnads.company.delete');
    Route::get('/brands/trash','c\CategoriesController@trashbrand')->name('brands.company.trash');

    Route::get('/products','c\CategoriesController@products');
    Route::get('/products/add','c\CategoriesController@addproducts')->name('add.company.products');
    Route::post('/products/addformpost','c\CategoriesController@addproductspost');
    Route::get('/products/edit/{id}','c\CategoriesController@editproduct');
    Route::post('/products/editpost/{id}','c\CategoriesController@editproductpost');
    Route::post('/products/deleteproductattribute','c\CategoriesController@deleteproductattribute');
    Route::get('/products/delete/{id}','c\CategoriesController@productdelete')->name('product.company.delete');


    Route::get('/products/trash','c\CategoriesController@producttrash')->name('trash.company.products');


    Route::post('/getsubcategories', 'c\CategoriesController@getsubcategories');




});


    Route::post('password/reset','EmailController@passwordreset');

    Route::post('set_passwordPost','EmailController@set_passwordPost');

    Route::get('/checkout-form' , 'HomeController@checkoutForm')->name('checkout.form');
    Route::post('/checout-form/post' , 'HomeController@Checkoutpost')->name('checkout-form.post');
    Route::get('/checkout/pay/{order}', 'HomeController@payView')->name('checkout.pay');
    Route::get('/transaction/pay/{id}' ,'HomeController@pay')->name('transaction');

    // Route::post('/cart/add/{id}','HomeController@cartadd')->name('cart.added');

    Route::get('/wishlist/add/{id}','HomeController@wishlist')->name('wishlist.add');

    // Route::get('/wishlist/update/{id}','HomeController@wishlistUpdate')->name('wishlist.update');
    Route::get('/home', 'HomeController@index')->name('home');
  

    Route::get('/customer/dashboard', 'HomeController@CustomerDashboard')->name('customer.dashboard');
    Route::get('/cart/items/{id}', 'HomeController@show')->name('cartitem.show');

// admin Middleware Section
Route::get('/c/register', 'Auth\AdminLoginController@showCompanyRegisterForm');
Route::post('/c/register', 'Auth\AdminLoginController@registercompany');
Route::get('/c/request', 'Auth\AdminLoginController@showCompanyRequestForm');
Route::post('/c/request', 'Auth\AdminLoginController@showCompanyRequestFormpost');

Route::get('/c/passwordreset', 'Auth\AdminLoginController@showPasswordResetForm');
Route::post('/c/passwordreset', 'Auth\AdminLoginController@showPasswordResetFormpost');




//Route::get('/admin/login', 'Auth\AdminLoginController@showLoginForm');
//Route::post('/admin/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
Route::get('/admin/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');

Route::prefix('admin')->middleware('auth:admin')->group(function() {
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/logout','Auth\AdminLoginController@logout')->name('admin.logout');

    //  Product dropdown route
    Route::get('/categories','CategoriesController@index');
    Route::get('/categories/form','CategoriesController@create');
    Route::post('/categories/form','CategoriesController@store')->name('add.categories');
    Route::get('/categories/form/{id}','CategoriesController@edit')->name('edit.categories');
    Route::post('/categories/form/{id}','CategoriesController@update')->name('update.categories');
    Route::get('/categories/delete{id}','CategoriesController@delete')->name('delete.categories');
    Route::get('/categories/trash','CategoriesController@categoriesTrash')->name('trash.categories');


    Route::get('/subcategories','CategoriesController@subcategories');
    Route::get('/subcategories/form','CategoriesController@subcategoriesform');
    Route::post('/subcategories/form','CategoriesController@subcategoriesformpost');

    Route::get('/subcategories/edit/{id}','CategoriesController@subcategoriesformedit');
    Route::post('/subcategories/formeditpost','CategoriesController@subcategoriesformeditpost');

    Route::post('/getsubcategories', 'CategoriesController@getsubcategories');

    // subcategories delet
    Route::get('/subcategories/delete/{id}','CategoriesController@subcategories_delet')->name('subcategories.delete');
    Route::get('/subcategories/trash','CategoriesController@trashsubcategories')->name('trash.subcategories');


    Route::get('/companies','CompaniesController@index');
    Route::get('/companies/edit/{id}','CompaniesController@editcompany');
    Route::post('/companies/formeditpost','CompaniesController@editcompanyformpost');
    Route::get('/companies/delete/{id}','CompaniesController@companydelete')->name('companies.delete');

app/products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class products extends Model
{
    //

    protected $table = 'products';

    public function order_item()
    {
       return $this->hasMany(OrderItem::class, 'product_id');
    }
   
    public function productQuantity()
    {
       return $this->hasMany(Productattributes::class, 'productid');
    }

    public function getDiscountedPriceAttribute()
    {
       if ($this->promotion_type == 'product' || $this->promotion_type == 'subcategory') {
          if ($this->promotion_type == 'product') {
            $discount = product_promotions::where('id' ,$this->all_offers)->where('disable_on_utc', '>', now())->first();
          } else {
            $discount = subcategory_promotions::where('id' ,$this->all_offers)->where('disable_on_utc', '>', now())->first();
          }
          if ($discount) {
            return ((100 - $discount->percentage) * $this->price) / 100;
          }
       }
       return null;
    }
  
   public function getVatAttribute() 
   {
      $price = $this->discounted_price ?? $this->price;
      return ($price * config('cart.tax')) / 100;
   }

   public function getMainImageAttribute()
   {
      $images = json_decode($this->image);
      if (isset($images[0])) {
         return asset('public/images/products/'.$images[0]);
      }
      return null;
   }

   public function getTotalAttribute()
   {
      $price = $this->discounted_price ?? $this->price;
      return $this->vat + $price;
   }
   
}   
   

resources/views/front-end/checkout.blade.php
@extends('layouts.front-app')
@section('content')

{{-- @php 
$cartCount = 0;
if (auth()->check()) {
    $cartCount = \App\Cart::where(['user_id' => auth()->id(), 'status' => 0])->get();
    $productclist = 
}
@endphp --}}

@if (\Session::has('danger'))
<div class="alert alert-danger">
<h3>{{ \Session::get('danger') }} </h3>
</div>
@endif


<div class="px-4 px-lg-0">
	<div class="pb-5">
        @php 
        $cartCount = Cart::count();
        @endphp
        
		@if($cartCount != 0)
		<div class="container py-5 text-center">
			<h2>{{ trans('checkout.Your Cart') }}</h2>
		</div>
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12 pl-5 pr-5 bg-white rounded">
					<div class="table-responsive">
						<table class="table cart-table" cellspacing="0">
							<thead>
								<tr>
									<th class="product-remove">&nbsp;</th>
									<th class="product-thumbnail">{{ trans('checkout.Image') }}</th>
									<th class="product-name">{{ trans('checkout.Product') }}</th>
									<th class="product-color">{{ trans('checkout.Color') }}</th>
									<th class="product-price">{{ trans('checkout.Price') }}</th>
									<th class="product-quantity">{{ trans('checkout.Quantity') }}</th>
									
									<th class="product-subtotal">{{ trans('checkout.Total') }}</th>
								</tr>
							</thead>
							<tbody>
                               
								@foreach ($cart as $item)
								@php $product = $item->product; @endphp
									<tr>
										<td class="product-remove">
											<a href="{{route('remove.cart',$item->rowId)}}" class="remove">
												<i class="fa fa-times"></i>
											</a>						
										</td>
										
										<td class="product-thumbnail">
                                            @if(\Session::get('locale') == 'ar')
                                            @foreach (json_decode($product->arabic_image) as $key => $products)
                                            @if($key == 0)
                                            <a href="#">
                                                <img width="100" width="100" src="{{asset('public/images/products/'.$products)}}" class="img-fluid rounded shadow-sm" alt="" >
                                            </a>
                                            @endif
                                            @endforeach
                                            @else
                                            @foreach (json_decode($product->image) as $key => $products)
                                            @if($key == 0)
                                            <a href="#">
                                                <img width="100" width="100" src="{{asset('public/images/products/'.$products)}}" class="img-fluid rounded shadow-sm" alt="" >
                                            </a>
                                            @endif
                                            @endforeach
                                            @endif
										</td>
										
										<td class="product-name">
										<a href="#">
                                            @if(\Session::get('locale') == 'ar')
                                            {{$product->arabic_name}}
                                            @else
                                            {{$product->prod_name}}
                                            @endif
                                        </a>
										</td>
										@php $options = []; @endphp
										@foreach ($item->attributes as $option)
											@php $options[] = ucfirst($option); @endphp
										@endforeach
										
										<td style="font-weight: bold;color:#000;">
											{{ implode(', ', $options) }}
										</td>

										<td class="product-price">
											<span class="amount">
												<bdi>
													<span class="currencySymbol">{{ trans('checkout.SR') }}</span>
                                                    {{$item->price}}
												</bdi>
											</span>
										</td>

										<td class="product-quantity" style="text-align: -webkit-center;">
											<div class="number-input md-number-input">
												<button onclick="this.parentNode.querySelector('input[type=number]').stepDown()" class="minus"></button>
												<input class="quantity" min="0" name="quantity" value="{{$item->qty}}" type="number">
												<button onclick="this.parentNode.querySelector('input[type=number]').stepUp()" class="plus"></button>
											</div>
										</td>
										<td class="product-subtotal">
											<span class="price-amount amount">
												<bdi>
													<span class="currencySymbol">{{ trans('checkout.SR') }}</span> {{$item->total}}
												</bdi>
											</span>						
										</td>
									</tr>
								@endforeach
								
							</tbody>
						</table>
					</div>
				</div>
			</div>
			@php 
				$subTotal = Cart::subtotal();
				$vat = number_format((config('cart.tax') * $subTotal) / 100, 2);
				$total = number_format($subTotal + $vat, 2);
			@endphp
			<div class="row bg-white">
                <div class="col-lg-6">
					<a href="{{ url('/') }}" type="button" style="    margin-top: 300px;" class="btn btn-dark  btn-primary">{{ trans('checkout.Continue Shoping') }}</a>
				</div>
                <div class="col-lg-6 rounded-pill">
					<div class="px-4 py-3 text-uppercase font-weight-bold" style="font-size:30px;">{{ trans('checkout.Cart totals') }}
					</div>
				  	<div class="p-4" style="border: 1px solid;">
					    <ul class="list-unstyled mb-4">
					    	<li class="d-flex justify-content-between py-3 border-bottom">
								<strong class="text-muted">{{ trans('checkout.Order Subtotal') }} </strong>
								
							<strong>{{ trans('checkout.SR') }} {{number_format($subTotal, 2)}}</strong>
					    	</li>
					      
					      	<li class="d-flex justify-content-between py-3 border-bottom">
							  <strong class="text-muted">{{ trans('checkout.VAT') }} {{config('cart.tax')}}%</strong>
					      		<strong>{{ trans('checkout.SR') }} {{$vat}}</strong>
					      	</li>
					      	<li class="d-flex justify-content-between py-3 border-bottom">
								  <strong class="text-muted">{{ trans('checkout.Total') }}</strong>
								
							  <h5 class="font-weight-bold"> {{ $total }}</h5>
					      	</li>
					    </ul>
				    	<a href="{{route('checkout.form')}}" class="btn btn-dark rounded py-2 btn-block btn-primary">{{ trans('checkout.Procceed to checkout') }}</a>
				  </div>
				</div>
            </div>
	
        </div>
        @else
        
        <div class="text-center">
			<p>{{ trans('checkout.There are no items in this cart') }}</p>
        	<a href="{{ url('/') }}" type="button" class="btn btn-dark  btn-primary">{{ trans('checkout.Continue Shoping') }}</a>
        </div>
        @endif
       
  	</div>
</div>

@endsection

resources/views/front-end/customer_dashboard.blade.php
@extends('layouts.front-app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-12">
			<div class="page-header">
				<h1 class="mt-3 mb-3">Dashboard</h1>
			</div>
		</div>	
	</div>
</div>		
<div class="container">
	<div class="row">
		<div class="col-lg-3 col-md-3 col-sm-6">
	    	<div class="tile tile-primary">
	            <div class="tile-heading">My Orders
				</div>
				@php
				$ordersCount = 0; 
				$ordersCount = \App\Orders::where(['user_id' => auth()->id()])->count();

				$wishlistCount = 0; 
				$wishlistCount = \App\Wishlist::where(['user_id' => auth()->id()])->count();
				@endphp
	            <div class="tile-body">
	                <i class="fa fa-get-pocket"></i>                    
	                <h2 class="pull-right">{{$ordersCount}}</h2>
	            </div>
	            <div class="tile-footer">
	                <a href="#">View more...</a>
	            </div>
	    	</div>
		</div>
		<div class="col-lg-3 col-md-3 col-sm-6">
	    	<div class="tile tile-primary">
	        	<div class="tile-heading">Wish list
	        	</div>
	            <div class="tile-body">
	                <i class="fa fa-heart-o"></i>
	                 <h2 class="pull-right">{{$wishlistCount}}</h2>
	            </div>
	            <div class="tile-footer">
	                <a href="#">View more...</a>
	            </div>
	    	</div>
		</div>
		<div class="col-lg-3 col-md-3 col-sm-6">
	    	<div class="tile tile-primary">
	        	<div class="tile-heading">Share
	        	</div>
	            <div class="tile-body">
	                <i class="fa fa-share-alt"></i>
	                <h2 class="pull-right">84</h2>
	            </div>
	            <div class="tile-footer">
	                <a href="#">View more...</a>
	            </div>
	    	</div>
		</div>
		<div class="col-lg-3 col-md-3 col-sm-6">
	    	<div class="tile tile-primary">
	        	<div class="tile-heading">Profile
	        	</div>
	            <div class="tile-body">
	                <i class="fa fa-user"></i>
	                <h2 class="pull-right">Muhammad</h2>
	            </div>
	            <div class="tile-footer">
	                <a href="#">View more...</a>
	            </div>
	    	</div>
		</div>
	</div>
</div>	

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="mt-3 mb-3">My Orders</h2>
			<table class="table table-striped">
			<thead>
				<tr>
				
					<th>Date</th>
					<th>Vat</th>
					<th>Total</th>
					<th>Shipping Price</th>
					<th>Subtotal</th>
					<th>Status</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				
				
                @foreach ($orderitem as $ordershow)
                    <tr class="text-center">
						
						<td>{{$ordershow->created_at}}</td> 
						<td>{{$ordershow->vat}}</td>
						<td>{{$ordershow->total}}</td>
						<td>{{$ordershow->shipping_price == '' ? 0 : $ordershow->shipping_price}}</td> 
						<td>{{$ordershow->subtotal}}</td> 
						<td>{{$ordershow->status}}</td>
						<td class="text-right">
							<div class="btn-group">
								<a class="btn btn-default" href="{{route('cartitem.show',$ordershow->id)}}">
									<i class="fa fa-eye"></i>
								</a>
							</div>
						</td>
					</tr>
					
                @endforeach
			  
				
				</tbody>
			</table>
		</div>	
	</div>	
</div>
<div class="container">
	<div class="row">
		<div class="col-md-12" style="text-align:center;">
	    	<a class="btn btn-primary mt-3 mb-3" href="#">View All Sale</a>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<h2 class="mt-3 mb-3">Wish List</h2>
		<table class="table table-striped">
			<thead>
				<tr>
					<th class="gc_cell_right">Product Image</th>
					<th class="gc_cell_right">Product name</th>
					<th class="gc_cell_right">Product Arbic name</th>
					<th class="gc_cell_right">Product Price</th>
					<th class="gc_cell_right">Action</th>
		           
		  		</tr>
			</thead>
			<tbody>
				@foreach ($wishlist as $wishlistitem)
					@php $product = $wishlistitem->products; @endphp
				<tr class="text-center">
					@foreach (json_decode($product->image) as $key => $itemimg)

					@if($key == 0)
						<td >
							<img src="{{asset('public/images/products/'.$itemimg)}}" height="50" width="50" alt="">
						</td>
					@endif
						
					@endforeach
					

					<td >{{$product->prod_name}}</td>
					<td >{{$product->arabic_name}}</td>
					<td >{{$product->price}}</td>
					<td >
						<div class="btn-group">
						<a class="btn btn-default" href="{{route('products.list',$product->id)}}">
								<i class="fa fa-eye"></i>
							</a>
						</div>
					</td>
		    	</tr>
				@endforeach
		       
		     
		    </tbody>
		</table>
	</div>
</div>
<div class="row">
    <div class="col-md-12" style="text-align:center;">
        <a class="btn btn-primary mt-3 mb-3" href="#">View All Wish List</a>
    </div>
</div>

<div class="container">
	<div class="row">
		<h2 class="mt-3 mb-3">Share</h2>
		<table class="table table-striped">
			<thead>
				<tr>
		            <th class="gc_cell_left">First Name</th>
		            <th>Last Name</th>
		            <th>Email</th>
		            <th class="gc_cell_right">Active </th>
		  		</tr>
			</thead>
			<tbody>
		        <tr class="text-center">
		        	<td class="gc_cell_left">Muhammad</td>
		        	<td>Abdullah</td>
		            <td>
		                <a href="mailto:sdfsdf@mali.com">Muhammadabdullah@mali.com</a>
		            </td>
		        	<td>Yes</td>
		    	</tr>
		       
		    </tbody>
		</table>
	</div>
</div>
<div class="row">
    <div class="col-md-12" style="text-align:center;">
        <a class="btn btn-primary mt-3 mb-3" href="#">View All Share</a>
    </div>
</div>    
    
@endsection

resources/views/front-end/help.blade.php
@extends('layouts.front-app')

@section('content')
<style>
   h1
   {
       font-size: 58px;
   }
</style>
<div class="container">
    <br>
    <br>
    <h1>{{ trans('help.Under Construction') }}</h1>
    <br>
    <br>
</div>
@endsection

resources/views/front-end/transaction.blade.php
@extends('layouts.front-app')
@section('content')

<div class="container">
    <div class="py-5 text-center">
        <h2>Payment</h2>
        <p class="lead">Need Some Informtion"</p>
    </div>
    <div class="stepwizard col-md-offset-3">
    	<div class="stepwizard-row setup-panel">
      		<div class="stepwizard-step">
        		<a href="#step-1" type="button" class="btn in-active-step btn-circle">1</a>
				<p>Account</p>
      		</div>
      		<div class="stepwizard-step">
        		<a href="#step-2" type="button" class="btn btn-default btn-circle in-active-step" disabled="disabled">2</a>
        		<p>Address</p>
      		</div>
      		<div class="stepwizard-step">
        		<a href="#step-3" type="button" class="btn btn-default btn-circle btn-primary" disabled="disabled">3</a>
        		<p>Payment</p>
      		</div>
    	</div>
  	</div>
    <div class="row">
        <div class="col-md-4 order-md-2 mt-4 mb-4 border-gray p-0">
            <div class="payment">
            	<h4 class="mt-3 ml-4">Cart - item(s)</h4>
            </div>	
    		@foreach ($order->orderitems as $item)
				<div class="col-md-12 mt-4 mb-4 border-bottom-img">
					<div class="row product-container">
						<div class="col-md-4 col-sm-4 col-xs-4">
							<div class="product-img">
							<img src="{{optional($item->product)->main_image}}" class="img-thumbnail rounded">
							</div>
						</div>
						<div class="col-md-8 col-sm-8 col-xs-8">
							<p class="product-text">{{$item->product_name}}</p>
							<p>{{$item->product_quantity}} x   SR{{$item->product_unit_price}}</p>
						</div>
					</div>	
				</div>
			@endforeach

    		<div class="payment">
            	<h4 class="mt-3 ml-4">Total</h4>
            </div>

    		<div class="col-md-12 mt-4 mb-4 border-bottom-img">
    			<div class="row product-container">
	        		<div class="col-md-12 col-sm-12 col-xs-12">
	            		<table class="table">
                			<tbody>
                				<tr>
                					<td> Subtotal:</td>
                					<td class="text-right">SR {{$order->subtotal}}</td>
                				</tr>
								<tr>
									<td>
										<strong>VAT:</strong>
									</td>
									<td class="text-right">
										<strong>SR {{$order->vat}}</strong>
									</td>
								</tr>
								{{-- <tr>
									<td>
										<strong>Shipping Price:</strong>
									</td>
									<td class="text-right">
										<strong>SR{{$order->shipping_price}}</strong>
									</td>
								</tr> --}}
  								<tr>
  									<td>
  										<strong>Total:</strong>
  									</td>
  									<td class="text-right">
  										<strong>SR {{$order->total}}</strong>
  									</td>
								  </tr>
								  <tr>
									  <td>
										{{-- <a href="{{route('transaction', encrypt($order->id))}}"  class="btn btn-success">Pay</a> --}}
									  </td>
								  </tr>
                			</tbody>
						</table>
						
					
	        		</div>
	        	</div>	
    		</div>
        </div>

        <div class="col-md-8 order-md-1 mt-4 mb-4">
            <div class="row">
                <div class="col-md-6">
					<h4 class="mt-3 ">Billing Address</h4>
					<strong>Name</strong>
					<br>
					<small>Email</small>
					<br>
					<small>Mobile</small>
				</div>
				
				<div class="col-md-6">
					<h4 class="mt-3">Shipping Address</h4>
					<strong>Name</strong>
					<br>
					<small>Email</small>
					<br>
					<small>Mobile</small>
                </div>
            </div>
        	{{-- <div class="row mt-3">
                <div class="col-md-6">
                    <div class="payment">
                        <h4 class="mt-3 ml-4">Payment Methods</h4>
                    </div>
                    <div class="shipping">
                        <p>Bank Transfer</p>
                        <p>Cash on Delivery</p>
                        <p>
                            <img class="img-fluid cc-img payment-img" src="https://saidaliah.me/9/uploads/offer/visa-logo.jpg" />
                        </p>
                    </div>
                    <div class="custom-control custom-checkbox mt-3 mb-3">
                        <input type="checkbox" class="custom-control-input" id="agree-terms">
                        <label class="custom-control-label" for="agree-terms">
                            <a href="#" target="_blank">I have read and agree to the Terms & Conditions</a>
                        </label>
					</div>
					
                </div>
                
            </div> --}}
        </div>
    </div>

    
</div>
@endsection